language: node_js
node_js:
  - '0.10'
addons:
  code_climate:
    repo_token: 72207598c2d5d4f105a0a3edb1d02c21e85b9c64748d40fc62f37620df932e0f
before_install:
  - gem install compass
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_script:
  - codeclimate < test/reports/coverage/*/lcov.info
env:
  global:
    - secure: GCnckgA+OB9QPimL7E3U/3ou1HTxv/m5eDkxPi2jF3prx1TkfJNe3zMw3Ve+AA39Rnw/pyXrpFIGajA5FLHJv7hV2cMWjhRiyUkmSFTMd+Xf58ogmV2tUWyBQxULFlNjMMQ28w+b8qVhGgQ+FcTanz//8RMZg+UDZ5DTiXaF+xg=
    - secure: jcan2L7Di589Jp/zzKXwLCiCvXIE10ZmQrfkGS8d7OWEo20KI9WPdK92fze8OyzUXPBm7hJxjqrWHS8L/etwE6eRUxPFt/ux+UHmWJm9PMRYZJPucN27wjCcOR+GPR3jDmIS6z7qm+zWJUh3jW0YxuJHiZpkjcV0cUGa4/vyV5c=
addons:
  sauce_connect: true
